data:extend({
	{
		type = "item",
		name = "craft-assistent-equipment",
		icon = "__morebobs_usefulsomething__/graphics/equipment/craft_assistent.png",
		icon_size = 32,
		placed_as_equipment_result = "craft-assistent-equipment",
		flags = {"goes-to-main-inventory"},
		subgroup = "equipment",
		order = "f[armor-pocket]-c[useful-equipment]",
		stack_size = 5,
		default_request_amount = 10
	},
	{
		type = "item",
		name = "artificial-organ-equipment",
		icon = "__morebobs_usefulsomething__/graphics/equipment/artificial_organ.png",
		icon_size = 32,
		placed_as_equipment_result = "artificial-organ-equipment",
		flags = {"goes-to-main-inventory"},
		subgroup = "equipment",
		order = "f[armor-pocket]-d[useful-equipment]",
		stack_size = 5,
		default_request_amount = 10
	},
	{
		type = "item",
		name = "portable-logistic-computer-equipment",
		icon = "__morebobs_usefulsomething__/graphics/equipment/portable_logistic_computer.png",
		icon_size = 32,
		placed_as_equipment_result = "portable-logistic-computer-equipment",
		flags = {"goes-to-main-inventory"},
		subgroup = "equipment",
		order = "f[armor-pocket]-f[useful-equipment]",
		stack_size = 5,
		default_request_amount = 10
	},
	{
		type = "item",
		name = "additional-toolbelt-equipment",
		icon = "__morebobs_usefulsomething__/graphics/icons/additional_toolbelt.png",
		icon_size = 32,
		placed_as_equipment_result = "additional-toolbelt-equipment",
		flags = {"goes-to-main-inventory"},
		subgroup = "equipment",
		order = "f[armor-pocket]-a[useful-equipment]",
		stack_size = 5,
		default_request_amount = 10
	},
	{
		type = "item",
		name = "armor-pocket-equipment",
		icon = "__morebobs_usefulsomething__/graphics/icons/armor-pocket.png",
		icon_size = 32,
		placed_as_equipment_result = "armor-pocket-equipment",
		flags = {"goes-to-main-inventory"},
		subgroup = "equipment",
		order = "f[armor-pocket]-b[useful-equipment]",
		stack_size = 5,
		default_request_amount = 10
	},
	{
		type = "item",
		name = "portable-autotrash-computer-equipment",
		icon = "__morebobs_usefulsomething__/graphics/equipment/portable-autotrash-computer.png",
		icon_size = 32,
		placed_as_equipment_result = "portable-autotrash-computer-equipment",
		flags = {"goes-to-main-inventory"},
		subgroup = "equipment",
		order = "f[armor-pocket]-g[useful-equipment]",
		stack_size = 5,
		default_request_amount = 10
	},
	{
		type = "item",
		name = "combet-control-module-equipment",
		icon = "__morebobs_usefulsomething__/graphics/equipment/combet-control-module.png",
		icon_size = 32,
		placed_as_equipment_result = "combet-control-module-equipment",
		flags = {"goes-to-main-inventory"},
		subgroup = "equipment",
		order = "f[armor-pocket]-e[useful-equipment]",
		stack_size = 5,
		default_request_amount = 10
	},
})