if data.raw["item"]["bullet-casing"] then
	data.raw["item"]["bullet-casing"].icon = "__morebobs__/graphics/icons/warfare/bullet-casing.png"
	data.raw["item"]["shotgun-shell-casing"].icon = "__morebobs__/graphics/icons/warfare/shotgun-shell-casing.png"
	data.raw["item"]["magazine"].icon = "__morebobs__/graphics/icons/warfare/mag-empty.png"
	--bullets
	data.raw["item"]["bullet"].icon = "__morebobs__/graphics/icons/warfare/bullet.png"
	data.raw["item"]["he-bullet"].icon = "__morebobs__/graphics/icons/warfare/he-bullet.png"
	data.raw["item"]["electric-bullet"].icon = "__morebobs__/graphics/icons/warfare/electric-bullet.png"
	data.raw["item"]["flame-bullet"].icon = "__morebobs__/graphics/icons/warfare/flame-bullet.png"
	data.raw["item"]["ap-bullet"].icon = "__morebobs__/graphics/icons/warfare/ap-bullet.png"
	data.raw["item"]["acid-bullet"].icon = "__morebobs__/graphics/icons/warfare/acid-bullet.png"
	data.raw["item"]["poison-bullet"].icon = "__morebobs__/graphics/icons/warfare/poison-bullet.png"
	--bullet projectiles
	data.raw["item"]["bullet-projectile"].icon = "__morebobs__/graphics/icons/warfare/bullet-projectile.png"
	data.raw["item"]["he-bullet-projectile"].icon = "__morebobs__/graphics/icons/warfare/he-bullet-projectile.png"
	data.raw["item"]["electric-bullet-projectile"].icon = "__morebobs__/graphics/icons/warfare/electric-bullet-projectile.png"
	data.raw["item"]["flame-bullet-projectile"].icon = "__morebobs__/graphics/icons/warfare/flame-bullet-projectile.png"
	data.raw["item"]["ap-bullet-projectile"].icon = "__morebobs__/graphics/icons/warfare/ap-bullet-projectile.png"
	data.raw["item"]["acid-bullet-projectile"].icon = "__morebobs__/graphics/icons/warfare/acid-bullet-projectile.png"
	data.raw["item"]["poison-bullet-projectile"].icon = "__morebobs__/graphics/icons/warfare/poison-bullet-projectile.png"
	--bullet magazines
	data.raw["ammo"]["bullet-magazine"].icon = "__morebobs__/graphics/icons/warfare/bullet-magazine.png"
	data.raw["ammo"]["he-bullet-magazine"].icon = "__morebobs__/graphics/icons/warfare/he-bullet-magazine.png"
	data.raw["ammo"]["electric-bullet-magazine"].icon = "__morebobs__/graphics/icons/warfare/electric-bullet-magazine.png"
	data.raw["ammo"]["flame-bullet-magazine"].icon = "__morebobs__/graphics/icons/warfare/flame-bullet-magazine.png"
	data.raw["ammo"]["ap-bullet-magazine"].icon = "__morebobs__/graphics/icons/warfare/ap-bullet-magazine.png"
	data.raw["ammo"]["acid-bullet-magazine"].icon = "__morebobs__/graphics/icons/warfare/acid-bullet-magazine.png"
	data.raw["ammo"]["poison-bullet-magazine"].icon = "__morebobs__/graphics/icons/warfare/poison-bullet-magazine.png"
	--shells
	data.raw["ammo"]["better-shotgun-shell"].icon = "__morebobs__/graphics/icons/warfare/shotgun-shell.png"
	data.raw["ammo"]["shotgun-explosive-shell"].icon = "__morebobs__/graphics/icons/warfare/shotgun-explosive-shell.png"
	data.raw["ammo"]["shotgun-electric-shell"].icon = "__morebobs__/graphics/icons/warfare/shotgun-electric-shell.png"
	data.raw["ammo"]["shotgun-flame-shell"].icon = "__morebobs__/graphics/icons/warfare/shotgun-flame-shell.png"
	data.raw["ammo"]["shotgun-ap-shell"].icon = "__morebobs__/graphics/icons/warfare/shotgun-ap-shell.png"
	data.raw["ammo"]["shotgun-acid-shell"].icon = "__morebobs__/graphics/icons/warfare/shotgun-acid-shell.png"
	data.raw["ammo"]["shotgun-poison-shell"].icon = "__morebobs__/graphics/icons/warfare/shotgun-poison-shell.png"
end